[shell]
program = "/usr/bin/fish"

[font]
normal = { family = "Hack Nerd Font",style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }

[window]
padding = { y = 8, x = 8 }
#opacity = 0.8

[scrolling]
history = 100000
multiplier = 3

[cursor]
style = { blinking = "Always" }
blink_interval = 500

[keyboard]
bindings = [
	{ key = "ArrowUp", mods = "Control", action = "ScrollPageUp" },
	{ key = "ArrowDown", mods = "Control", action = "ScrollPageDown" },

	{ key = "ArrowUp", mods = "Control | Shift", action = "ScrollHalfPageUp" },
	{ key = "ArrowDown", mods = "Control | Shift", action = "ScrollHalfPageDown" },

	{ key = "K", mods = "Control", chars = "printf \"\\033c\"\n"  },

	{ key = "F", mods = "Control", action = "SearchForward" },
	{ key = "F", mods = "Control | Shift", action = "SearchBackward" }
]

# Colors (Dracula)

# Default colors
[colors.primary]
background = '#282a36'
foreground = '#f8f8f2'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#ff5555'
green   = '#50fa7b'
yellow  = '#f1fa8c'
blue    = '#bd93f9'
magenta = '#ff79c6'
cyan    = '#8be9fd'
white   = '#bbbbbb'

# Bright colors
[colors.bright]
black   = '#555555'
red     = '#ff5555'
green   = '#50fa7b'
yellow  = '#f1fa8c'
blue    = '#caa9fa'
magenta = '#ff79c6'
cyan    = '#8be9fd'
white   = '#ffffff'