[terminal.shell]
program = "/usr/bin/fish"

[font]
normal = { family = "Hack Nerd Font",style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }

[window]
padding = { y = 3, x = 3 }

[scrolling]
history = 100000
multiplier = 3

[cursor]
style = { blinking = "Always" }
blink_interval = 500

[keyboard]
bindings = [
	{ key = "ArrowUp", mods = "Control", action = "ScrollPageUp" },
	{ key = "ArrowDown", mods = "Control", action = "ScrollPageDown" },

	{ key = "ArrowUp", mods = "Control | Shift", action = "ScrollHalfPageUp" },
	{ key = "ArrowDown", mods = "Control | Shift", action = "ScrollHalfPageDown" },

	{ key = "K", mods = "Control", chars = "printf \"\\033c\"\n"  },

	{ key = "F", mods = "Control", action = "SearchForward" },
	{ key = "F", mods = "Control | Shift", action = "SearchBackward" }
]

[terminal]

# Colors (Gruvbox dark)

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'